name: Scheduled Simple Test

on:
  schedule:
    - cron: '*/10 * * * *'
  

  workflow_dispatch: 

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a simple test script
        run: |
          echo "Running scheduled smoke tests..."
          echo "Current time is $(date)"
